# docker-compose.yml
version: '3.8'
services:
  frontend:
    build:
      context: ./test-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
      
  backend:
    build:
      context: ./test1
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/thisdata2?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - database
    networks:
      - app-network
      
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: thisdata2
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:


